idf_component_register(SRCS "main.c"
					SRCS "components/common/common.c"
					SRCS "components/node/node.c"
					SRCS "components/wifi/wifi.c"
					SRCS "components/nvs_mgmt/nvs_mgmt.c"
					SRCS "components/adc/adc.c"
					SRCS "components/conf/conf.c"
					INCLUDE_DIRS "components/common"
					INCLUDE_DIRS "components/node"
					INCLUDE_DIRS "components/wifi"
					INCLUDE_DIRS "components/nvs_mgmt"
					INCLUDE_DIRS "components/adc"
					INCLUDE_DIRS "components/conf"
                    REQUIRES driver nvs_flash esp_wifi esp_adc
					REQUIRES console)